## Build
FROM golang:1.19-alpine AS build

RUN apk add --no-cache ca-certificates openssl
RUN /usr/sbin/update-ca-certificates

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY main.go ./
COPY var/ ./var/

RUN ls -l ./
RUN go build -o ./main

ENV TZ=America/New_York
COPY ./var/$TZ /usr/share/zoneinfo/$TZ
COPY ./var/$TZ /etc/localtime

ENTRYPOINT ["./main"]